services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./static:/usr/share/nginx/html:ro
      - ./nginx/cache:/var/cache/nginx:rw
    depends_on:
      - app-main
      - app-read-1
      - app-read-2
      - db
      - pgadmin
    restart: unless-stopped

  db: 
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${PSQL_NAME}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PSQL_USER} -d ${PSQL_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d:ro

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    expose:
      - "80"
    restart: unless-stopped
  migration:
    build:
      context: ./
      dockerfile: hardware_store/build/migrator/Dockerfile
    env_file:
    - ./hardware_store/.env
    command:
    - sh
    - -c
    - |
      goose -dir migrations postgres \
        "host=db port=5432 user=$$PSQL_USER password=$$PSQL_PASSWORD dbname=$$PSQL_NAME sslmode=disable" \
        up
    depends_on:
      db:
        condition: service_healthy

  app-main:
    build:
      context: ./
      dockerfile: hardware_store/build/server/Dockerfile
    container_name: app-main
    expose:
      - "8081"
    env_file:
      - ./hardware_store/.env
    environment:
      - SERVER_PORT=8081
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${PSQL_USER}
      - DB_PASSWORD=${PSQL_PASSWORD}
    depends_on:
      migration:
        condition: service_completed_successfully
      db:
        condition: service_healthy

  app-read-1:
    build:
      context: ./
      dockerfile: hardware_store/build/server/Dockerfile
    container_name: app-read-1
    expose:
      - "8081"
    env_file:
      - ./hardware_store/.env
    environment:
      - SERVER_PORT=8081
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${PSQL_READ_USER}
      - DB_PASSWORD=${PSQL_READ_PASSWORD}
    depends_on:
      migration:
        condition: service_completed_successfully
      db:
        condition: service_healthy

  app-read-2:
    build:
      context: ./
      dockerfile: hardware_store/build/server/Dockerfile
    container_name: app-read-2
    expose:
      - "8081"
    env_file:
      - ./hardware_store/.env
    environment:
      - SERVER_PORT=8081
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${PSQL_READ_USER}
      - DB_PASSWORD=${PSQL_READ_PASSWORD}
    depends_on:
      migration:
        condition: service_completed_successfully
      db:
        condition: service_healthy

  auth-migrations:
    build:
      context: ./auth-service
      dockerfile: build/server/Dockerfile
    container_name: auth-migrations
    environment:
      - STORAGE_PATH=/app/storage/auth.db
    volumes:
      - pg-auth:/storage    
    entrypoint: ["/bin/goose"]
    command: ["-dir", "/app/migrations", "sqlite3", "/storage/auth.db", "up"]

  auth-service:
    build:
      context: ./auth-service 
      dockerfile: build/server/Dockerfile
    container_name: auth-service
    ports:
      - "9090:9090" 
    env_file:
      - ./auth-service/.env
    environment:
      - SERVER_PORT=9090
      - CONFIG_PATH=/app/config/local.yaml 
      - STORAGE_PATH=/app/storage/auth.db
    volumes:
      - pg-auth:/app/storage
    depends_on:
      auth-migrations:
        condition: service_completed_successfully

volumes:
  pg:
  pg-auth:
